version: '3.4'

services:
  invilliaddd.server:
    image: ${DOCKER_REGISTRY-}invilliadddserver
    build:
      context: .
      dockerfile: FrontEnd\InvilliaDDD.Server\Dockerfile

  invilliaddd.gamemanager.api:
    image: ${DOCKER_REGISTRY-}invilliadddgamemanagerapi
    build:
      context: .
      dockerfile: InvilliaDDD.Games.API\Dockerfile


  invilliaddd.identity.api:
    image: ${DOCKER_REGISTRY-}invilliadddidentityapi
    build:
      context: .
      dockerfile: InvilliaDDD.Identity.API\Dockerfile

  invilliaddd.sqlserver:
    container_name: sqlserver
    image: msbowelite/sql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Insecure!12345"
      ACCEPT_EULA: "Y"

